// <auto-generated />
using System;
using Infrastructure.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(RssReaderDbContext))]
    partial class RssReaderDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("Roles", "auth");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "SuperAdmin"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Admin"
                        },
                        new
                        {
                            Id = 3,
                            Name = "User"
                        });
                });

            modelBuilder.Entity("Domain.Entities.RssFeed", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ChannelTitle")
                        .HasColumnType("text");

                    b.Property<string>("Url")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("RssFeeds", "feeds");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ChannelTitle = "Test Feed 1 Technologie Nachrichten und neue Entwicklungen",
                            Url = "https://www.spiegel.de/politik/index.rss"
                        },
                        new
                        {
                            Id = 2,
                            ChannelTitle = "Test Feed 2 Wissenschaft - WELT",
                            Url = "https://www.welt.de/feeds/section/wissenschaft.rss"
                        });
                });

            modelBuilder.Entity("Domain.Entities.RssFeedItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<string>("Link")
                        .HasColumnType("text");

                    b.Property<DateTime>("PublishDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("RssFeedId")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RssFeedId");

                    b.ToTable("RssFeedItems", "feeds");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Bundesarbeitsminister Heil will den Einsatz von Künstlicher Intelligenz (KI) in der Arbeitswelt vorantreiben. Arbeit werde sich verändern, aber nicht ausgehen, so Heil. In seinem Ministerium gebe es dazu bereits eine Denkfabrik.",
                            ImageUrl = "https://images.tagesschau.de/image/8616ee35-2c95-46f8-b8b5-0f5da2c4b359/AAABiL5ZIxM/AAABkZLhkrw/16x9-1280/roboter-ki-100.jpg",
                            Link = "https://www.tagesschau.de/wirtschaft/digitales/spd-heil-ki-arbeitswelt-100.html",
                            PublishDate = new DateTime(2024, 4, 21, 10, 30, 0, 0, DateTimeKind.Utc),
                            RssFeedId = 1,
                            Title = "Test Feed Item 1 Künstliche Intelligenz; Arbeitsminister Heil will KI \"auf die Straße bringen"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Test Feed Item 2 Bei der Messe IAA Mobility in München setzen die Autobauer besonders ihre E-Autos in Szene. Die Botschaft: Die Zukunft ist elektrisch. Doch wann kommt der angekündigte Durchbruch der E-Mobilität? Von Sebastian Hanisch.",
                            ImageUrl = "https://images.tagesschau.de/image/ddd57310-c336-49f4-9351-067576add465/AAABimEJjZ0/AAABkZLhkrw/16x9-1280/iaa-200.jpg",
                            Link = "https://testlink2.com/",
                            PublishDate = new DateTime(2024, 4, 21, 10, 30, 0, 0, DateTimeKind.Utc),
                            RssFeedId = 1,
                            Title = "Test Feed Item 2 IAA Mobility: Wann schaffen E-Autos den Durchbruch in Deutschland?"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Test Feed Item 3 Ob Staubsauger, Herd oder Lampen - Haushaltselektronik wird immer schlauer und macht das Zuhause zum \"Smart Home\". Die intelligente Vernetzung breitet sich aus und ist auch bei auf heute beginnenden IFA ein Thema. Von Ole Hilgert.",
                            ImageUrl = "https://images.tagesschau.de/image/132ad0ce-c2a4-4b80-893f-d5236a39891f/AAABikx6AhE/AAABkZLhkrw/16x9-1280/ifa-2023-100.jpg",
                            Link = "https://www.tagesschau.de/wirtschaft/digitales/ifa-smart-home-102.html",
                            PublishDate = new DateTime(2024, 4, 21, 10, 30, 0, 0, DateTimeKind.Utc),
                            RssFeedId = 1,
                            Title = "Test Feed Item 3 Elektronikmesse IFA: Der Weg zum intelligenten Zuhause"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Test Feed Item 4 Ausgedehnte Riffe vor den europäischen Küsten – das war einmal. Aber nicht Korallen, sondern einheimische Austern waren die Basis. Diese existieren nur noch vereinzelt in Nordsee und Atlantik, aber das soll sich durch die Wiederansiedlung ändern",
                            ImageUrl = "https://img.welt.de/img/wissenschaft/mobile253832924/1181622987-ci23x11-w780/France-Normandy-Manche-department-Cotentin-Saint-Vaast-la-Hougue-lle-de-Tat.jpg",
                            Link = "https://www.welt.de/wissenschaft/article253832928/Europaeische-Austern-Muscheln-aus-der-Zucht-sollen-neue-Riffe-bilden.html",
                            PublishDate = new DateTime(2024, 4, 21, 10, 30, 0, 0, DateTimeKind.Utc),
                            RssFeedId = 1,
                            Title = "Test Feed Item 4 Zuchtmuscheln sollen wieder Riffe bilden"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Test Feed Item 5 Die Form ist entscheidend: Menschen nehmen Informationen unterschiedlich wahr – und zwar abhängig davon, auf welche Weise ihnen Zahlen präsentiert werden. Italienische Forscher haben untersucht, wie sich das zum Beispiel auf das Thema Migration auswirkt.",
                            ImageUrl = "https://img.welt.de/img/wissenschaft/mobile253829762/5701629567-ci23x11-w780/Beer-Fest-from-within-tent.jpg",
                            Link = "https://www.welt.de/wissenschaft/article253829764/Gefuehltes-Verhaeltnis-Warum-zwei-von-50-mehr-klingt-als-vier-Prozent.html",
                            PublishDate = new DateTime(2024, 4, 21, 10, 30, 0, 0, DateTimeKind.Utc),
                            RssFeedId = 1,
                            Title = "Test Feed Item 5 Zwei von 50 Menschen – sind nur vier Prozent"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Test Feed Item 6 Eine Grenze, mitten durch Deutschland: Nicht nur die Nation war über Jahrzehnte geteilt, sondern auch die Tierwelt. Der fast 1400 Kilometer lange Todesstreifen ist heute ein „Grünes Band“. Trotzdem bleiben die Tiere im Osten und die im Westen unter sich – aus bemerkenswerten Gründen.",
                            ImageUrl = "https://img.welt.de/img/wissenschaft/mobile253834946/0941626977-ci23x11-w780/DWO-WS-Teaser-Ost-West-Tiere-mku-cw-jpg.jpg",
                            Link = "https://www.welt.de/wissenschaft/plus253801310/West-und-ostdeutsche-Natur-Warum-durch-die-Tierwelt-noch-immer-eine-Grenze-verlaeuft.html",
                            PublishDate = new DateTime(2024, 4, 21, 10, 30, 0, 0, DateTimeKind.Utc),
                            RssFeedId = 1,
                            Title = "Test Feed Item 6 Warum sich Deutschland für Mäuse, Igel, Krähen und andere Tiere in Ost und West teilt"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Bundesarbeitsminister Heil will den Einsatz von Künstlicher Intelligenz (KI) in der Arbeitswelt vorantreiben. Arbeit werde sich verändern, aber nicht ausgehen, so Heil. In seinem Ministerium gebe es dazu bereits eine Denkfabrik.",
                            ImageUrl = "https://images.tagesschau.de/image/8616ee35-2c95-46f8-b8b5-0f5da2c4b359/AAABiL5ZIxM/AAABkZLhkrw/16x9-1280/roboter-ki-100.jpg",
                            Link = "https://www.tagesschau.de/wirtschaft/digitales/spd-heil-ki-arbeitswelt-100.html",
                            PublishDate = new DateTime(2024, 4, 21, 10, 30, 0, 0, DateTimeKind.Utc),
                            RssFeedId = 2,
                            Title = "Test Feed Item 7 Künstliche Intelligenz; Arbeitsminister Heil will KI \"auf die Straße bringen"
                        },
                        new
                        {
                            Id = 8,
                            Description = "Test Feed Item 2 Bei der Messe IAA Mobility in München setzen die Autobauer besonders ihre E-Autos in Szene. Die Botschaft: Die Zukunft ist elektrisch. Doch wann kommt der angekündigte Durchbruch der E-Mobilität? Von Sebastian Hanisch.",
                            ImageUrl = "https://images.tagesschau.de/image/ddd57310-c336-49f4-9351-067576add465/AAABimEJjZ0/AAABkZLhkrw/16x9-1280/iaa-200.jpg",
                            Link = "https://testlink2.com/",
                            PublishDate = new DateTime(2024, 4, 21, 10, 30, 0, 0, DateTimeKind.Utc),
                            RssFeedId = 2,
                            Title = "Test Feed Item 8 IAA Mobility: Wann schaffen E-Autos den Durchbruch in Deutschland?"
                        },
                        new
                        {
                            Id = 9,
                            Description = "Test Feed Item 3 Ob Staubsauger, Herd oder Lampen - Haushaltselektronik wird immer schlauer und macht das Zuhause zum \"Smart Home\". Die intelligente Vernetzung breitet sich aus und ist auch bei auf heute beginnenden IFA ein Thema. Von Ole Hilgert.",
                            ImageUrl = "https://images.tagesschau.de/image/132ad0ce-c2a4-4b80-893f-d5236a39891f/AAABikx6AhE/AAABkZLhkrw/16x9-1280/ifa-2023-100.jpg",
                            Link = "https://www.tagesschau.de/wirtschaft/digitales/ifa-smart-home-102.html",
                            PublishDate = new DateTime(2024, 4, 21, 10, 30, 0, 0, DateTimeKind.Utc),
                            RssFeedId = 2,
                            Title = "Test Feed Item 9 Elektronikmesse IFA: Der Weg zum intelligenten Zuhause"
                        },
                        new
                        {
                            Id = 10,
                            Description = "Test Feed Item 4 Ausgedehnte Riffe vor den europäischen Küsten – das war einmal. Aber nicht Korallen, sondern einheimische Austern waren die Basis. Diese existieren nur noch vereinzelt in Nordsee und Atlantik, aber das soll sich durch die Wiederansiedlung ändern",
                            ImageUrl = "https://img.welt.de/img/wissenschaft/mobile253832924/1181622987-ci23x11-w780/France-Normandy-Manche-department-Cotentin-Saint-Vaast-la-Hougue-lle-de-Tat.jpg",
                            Link = "https://www.welt.de/wissenschaft/article253832928/Europaeische-Austern-Muscheln-aus-der-Zucht-sollen-neue-Riffe-bilden.html",
                            PublishDate = new DateTime(2024, 4, 21, 10, 30, 0, 0, DateTimeKind.Utc),
                            RssFeedId = 2,
                            Title = "Test Feed Item 10 Zuchtmuscheln sollen wieder Riffe bilden"
                        },
                        new
                        {
                            Id = 11,
                            Description = "Test Feed Item 5 Die Form ist entscheidend: Menschen nehmen Informationen unterschiedlich wahr – und zwar abhängig davon, auf welche Weise ihnen Zahlen präsentiert werden. Italienische Forscher haben untersucht, wie sich das zum Beispiel auf das Thema Migration auswirkt.",
                            ImageUrl = "https://img.welt.de/img/wissenschaft/mobile253829762/5701629567-ci23x11-w780/Beer-Fest-from-within-tent.jpg",
                            Link = "https://www.welt.de/wissenschaft/article253829764/Gefuehltes-Verhaeltnis-Warum-zwei-von-50-mehr-klingt-als-vier-Prozent.html",
                            PublishDate = new DateTime(2024, 4, 21, 10, 30, 0, 0, DateTimeKind.Utc),
                            RssFeedId = 2,
                            Title = "Test Feed Item 11 Zwei von 50 Menschen – sind nur vier Prozent"
                        },
                        new
                        {
                            Id = 12,
                            Description = "Test Feed Item 6 Eine Grenze, mitten durch Deutschland: Nicht nur die Nation war über Jahrzehnte geteilt, sondern auch die Tierwelt. Der fast 1400 Kilometer lange Todesstreifen ist heute ein „Grünes Band“. Trotzdem bleiben die Tiere im Osten und die im Westen unter sich – aus bemerkenswerten Gründen.",
                            ImageUrl = "https://img.welt.de/img/wissenschaft/mobile253834946/0941626977-ci23x11-w780/DWO-WS-Teaser-Ost-West-Tiere-mku-cw-jpg.jpg",
                            Link = "https://www.welt.de/wissenschaft/plus253801310/West-und-ostdeutsche-Natur-Warum-durch-die-Tierwelt-noch-immer-eine-Grenze-verlaeuft.html",
                            PublishDate = new DateTime(2024, 4, 21, 10, 30, 0, 0, DateTimeKind.Utc),
                            RssFeedId = 2,
                            Title = "Test Feed Item 12 Warum sich Deutschland für Mäuse, Igel, Krähen und andere Tiere in Ost und West teilt"
                        });
                });

            modelBuilder.Entity("Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasAnnotation("RegularExpression", "^\\w+([-+.']\\w+)*@\\w+([-.]\\w+)*\\.\\w+([-.]\\w+)*$");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("text");

                    b.Property<DateTime?>("RefreshTokenExpiryTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("RssFeedId")
                        .HasColumnType("integer");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("RssFeedId");

                    b.ToTable("Users", "auth");
                });

            modelBuilder.Entity("Domain.Entities.UserRole", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles", "auth");
                });

            modelBuilder.Entity("RssFeedUser", b =>
                {
                    b.Property<int>("RssFeedsId")
                        .HasColumnType("integer");

                    b.Property<int>("UsersId")
                        .HasColumnType("integer");

                    b.HasKey("RssFeedsId", "UsersId");

                    b.HasIndex("UsersId");

                    b.ToTable("RssFeedUser");
                });

            modelBuilder.Entity("Domain.Entities.RssFeedItem", b =>
                {
                    b.HasOne("Domain.Entities.RssFeed", "RssFeed")
                        .WithMany("FeedItems")
                        .HasForeignKey("RssFeedId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RssFeed");
                });

            modelBuilder.Entity("Domain.Entities.User", b =>
                {
                    b.HasOne("Domain.Entities.RssFeed", "RssFeed")
                        .WithMany()
                        .HasForeignKey("RssFeedId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("RssFeed");
                });

            modelBuilder.Entity("Domain.Entities.UserRole", b =>
                {
                    b.HasOne("Domain.Entities.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("RssFeedUser", b =>
                {
                    b.HasOne("Domain.Entities.RssFeed", null)
                        .WithMany()
                        .HasForeignKey("RssFeedsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UsersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Entities.Role", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("Domain.Entities.RssFeed", b =>
                {
                    b.Navigation("FeedItems");
                });

            modelBuilder.Entity("Domain.Entities.User", b =>
                {
                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
